### ISSUE TITLE
Font resizing with window

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#112]
**Bug Description**
Not certain if this is a bug or a planned behavior however when changing the size of QPrompt's window, the font resizes instead of rewrapping to fit the available width maintaining font size... vertical cropping works as expected

**Steps to Reproduce**
1. Drag resize handle with default Welcome text
2.  Text lines resize to fit available width, embedded jpg logo does not resize.

**Expected behavior**
Not certain if text should reflow to fit available width at current size.

**Screenshots** (optional)
![screen](https://user-images.githubusercontent.com/88691671/184462986-3c245919-b42a-411e-80be-7eafa3d1b26c.png)

**Device information**
 - Operating System: Raspberry Pi or Debian - both Bullseye with latest updates

**Comment by Cuperino** [comment]
This is intended behavior. It is intended for the prompter, and for the editor only when it shows the same font size as the prompter. A decoupled editor wouldn't need to follow this behavior.
