### ISSUE TITLE
QPrompt save obscures interface controls intermittently

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#113]
**Bug Description**
When saving scripts after prolonged activity in QPrompt, the Saved message overlays controls (dependent on current resolution, usually lower like 480p) persists for an extended period of time, blocking mouse access to those controls.

**Steps to Reproduce**
1. Set resolution to 480p
2. Work with a 3-5 page script for a extended period of time (>20 minutes)
3. Save script.

**Expected behavior**
Message should disappear after a brief display duration

**Screenshots** (optional)
![screen02](https://user-images.githubusercontent.com/88691671/184463750-0eebb982-b709-4d54-88c2-72e2f7cb382b.png)
![183270732-8ac333f4-b160-4308-81d2-93dd10c0d476](https://user-images.githubusercontent.com/88691671/184463751-b880f217-3391-4dfa-9d7f-2ff18c6cf86e.png)

**Device information**
 - Operating System: Raspberry Pi Bullseye/400, latest updates

**Comment by Cuperino** [comment]
This is intended behavior. It is only intended for the prompter and the editor only when it reflects the same font size as the prompter. A decoupled editor wouldn't need to follow this behavior.

**Comment by Cuperino** [comment]
The duration of "passive notifications", as they're called in Kirigami, is currently set to Kirigami's default, which is subject to vary according to the amount of text being notified. I can shorten the duration to a fixed or alternate variable duration if so desired.

How many seconds do save notifications currently persist on your Raspberry Pi?

**Comment by videosmith** [comment]
it varies between 3-10 seconds for some reason, perhaps the size of the file writing to the SD card affects the message display time?

It would not matter as much if the message was displayed in an area devoid of controls... perhaps it could be moved to the windows top bar where the file name is displayed?

To be honest, the addition of an asterisk to the top bar filename when files are modified and it's removal when saved is adequate for me, the other notification is not really necessary.

**Comment by videosmith** [comment]
Just tried resaving your Welcome file as test.html on a Dell Insporion 15's hard disk (Debian Bullseye, latest updates).
The message was displayed for ~15 seconds.

**Comment by Cuperino** [comment]
The duration may have to do with the length of the path to the saved file. File size may affect duration, but hardly by that many seconds.

I'll make it so QPrompt only notifies the first time that you save a file, or when you save as.

**Comment by Cuperino** [comment]
Re-opening due to user requesting for visual feedback to be added in full screen mode, where the title bar isn't visible.

I would be enabling the notification there or perhaps use a different shorter notification if the file isn't being saved for the first time.
