### ISSUE TITLE
Font resize not working in certain circumstances

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#114]
**Bug Description**
Not certain if this is related to #107, #108, however when loading saved .html files, Font Size slider and 'Small Fonts' button do not work (although the cursor does continue to resize)

**Steps to Reproduce**
1. Went to lorem ipsum generator website, created 5 paragraphs
2. Copied from website, ctrl/shift/v pasted into QPrompt
3. Adjusting Font Slider works as expected
4. Save as .html file.
5. Select New in QPrompt, load .html file
6. Slider does not affect text, only cursor and margins
7. Workaround, open .html file in word processor, copy and ctrl/shift/v into QPrompt
8.  Slider affects Font Size correctly
9. If copy/paste performed via browser like Chromium paragraphs now multi-spaced 

**Expected behavior**
Font Slider operation and formatting should be retained

**Screenshots** (optional)
![screen](https://user-images.githubusercontent.com/88691671/184466144-e78821cc-7897-4c59-aa88-dde264381237.png)
![screen01](https://user-images.githubusercontent.com/88691671/184466146-a734e333-970f-4fc0-a8af-fa392fc45767.png)
![screen02](https://user-images.githubusercontent.com/88691671/184466147-4f0f9e1f-d49d-4fc9-aae1-d6bcfb2c8993.png)
![screen03](https://user-images.githubusercontent.com/88691671/184466171-9decf8bb-97c1-4ae1-813b-8ac8d2001c44.png)

**Device information**
 - Operating System: Raspberry Pi/Debian - Bullseye, latest updates

**Comment by Cuperino** [comment]
It's the same bug as #107. My bad for not documenting that properly. The bug has been fixed for the next release.

Here's the workaround I gave David over at Telegram, which you can use until I'm able to release the v1.1.1 update:

> I hadn't realized this, but Qt is saving letter-spacing, word-spacing, and font-size settings into the exported HTML file. By doing so, it prevents those sliders from working because they operate under the presumption that those values aren't specified in the document. The values from the document then override those from the sliders, preventing them from working.
>
>To work around the issue, open any file you saved from QPrompt using Notepad or any other basic text editor. Go to line 4, where you will find something like this:
><body style=" font-family:'DejaVu Sans'; font-weight:400; font-style:normal; letter-spacing:0px; word-spacing:12.4375px;">
>And remove the style properties from the body tag. The body tag should look like:
><body>
>
>QPrompt v1.1 automatically reloads open documents if they're modified from another software. Meaning you can clean the body tag from another program without having to re-open the file in QPrompt and the sliders will instantly work again.

Since the bug has already been fixed on the main branch, you could also make your own build following [these instructions](https://github.com/Cuperino/QPrompt/issues/38#issuecomment-1011693418).

**Comment by videosmith** [comment]
> QPrompt v1.1 automatically reloads open documents if they're modified from another software.

This can be very useful until NDI becomes available *thumbs up*

Is it possible to load in a networked text file like a media player by adding the URL instead of a local file path?
![url](https://user-images.githubusercontent.com/88691671/184511527-dd101eef-dd14-4219-8245-8e6c57df16af.png)

**Comment by Cuperino** [comment]
The auto-refreshing functionality can be made to work with remote files. Adding support for remote files is a little more complex as there are different protocols that could be used. In the case of cloud storage services, such as Google Drive, one would be required to use a dedicated API to access those files, which is a separate and exclusive mechanism for accessing those files. Having said that, I plan on adding support for Google Drive, NextCloud and Own Cloud in the future.
