### ISSUE TITLE
QPrompter Width

### ISSUE THREAD

**Issue by AlwaysBDV** [Cuperino/QPrompt#123]
**Is your feature request related to a problem or a limitation? Please describe...**
I just DL QP and look forward to using it.  I believe it will solve problems for me.  Just one thing thought, unless it is there and I missed it.  Can the margins be changed?  I prefer to read down the center of the screen only.  The wider screen is great for editing, but when prompting it requires one to dart their eyes from left to right.  I would prefer the viewer to not be distracted by that.

**Describe the solution you'd prefer**

**Describe alternatives you've considered**

**Provide use examples**

**Comment by Cuperino** [comment]
> Can the margins be changed?

Yes. Simply drag the vertical line to the left of the editor to adjust its width. You can also adjust the vertical offset by adjusting the vertical line at the right.

**Comment by Cuperino** [comment]
![Screen Shot](https://user-images.githubusercontent.com/1840407/186521109-98751fdb-a00e-4ee8-a3fc-3e8be326e2d3.jpg)
