### ISSUE TITLE
Add option to enable multithreaded renderer at launch

### ISSUE THREAD

**Issue by Cuperino** [Cuperino/QPrompt#127]
### Possible solutions

1. Parse terminal / command line options to determine whether the hack would run or not. (I don't know if Qt's parser would work here. If it won't, this would have to be programmed without relying on Qt. This approach is cleaner because the interface can be self documented and users would be able to learn about it by running `qprompt -h`, which does nothing at present).
2. Make use of an extra, custom, environment variable to determine whether the hack is to be run on not. (This is basically a hack to work around the hack, and it is certain to work.).

**Comment by Cuperino** [comment]
@videosmith, The option to re-enable the multi-threaded renderer is ready to be released. I went with option number one of the ones proposed here: https://github.com/Cuperino/QPrompt/issues/127.

Now I'm going to try fixing at least one other long standing bug before making the next minor release; because each release triggers updates for Snapcraft and Flatpak users, and the option to re-enable the multi-threaded renderer is something only very few people will use.

**Comment by videosmith** [comment]
Thank you
