### ISSUE TITLE
Make prompter x-offset feature noticeable

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#152]
Occasionally due to camera placement, the prompter is pointed away from talent center.

If you could move either the left or right margin as well as both, then you could reposition the text on the left or right side of the monitor.

![screen](https://user-images.githubusercontent.com/88691671/216110493-fcd206fb-2680-40a0-9fac-bdf225ba2747.jpg)

**Comment by Cuperino** [comment]
Please expand more on this? I'm not sure that I'm following.

So far I understand you'd like to be able to drag and re-size from either handle. I'm afraid that would be problematic for use in touch displays, such as tablets, where having each handle do one thing means you don't need to press something else to toggle how you're making adjustments.

I can modify the extent to which each of these handles can go, but going out of bounds can be dangerous because one could end up accidentally placing the handles out of bounds, and have no means to return but manually alter or delete the program's configuration.

**Comment by videosmith** [comment]
Currently when you drag one margin, the other follows, somewhat like a center-justified margin resize.Is a left or right-justified margin resize (not the text itself) possible? This would also allow for a video jnsert for interrotron/video conference applications.
    On Wednesday, February 1, 2023, 03:03:40 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Please expand more on this? I'm not sure that I'm following.

So far I understand you'd like to be able to drag and re-size from either handle. I'm afraid that would be problematic for use in touch displays, such as tablets, where having each handle do one thing means you don't need to press something else to toggle how you're making adjustments.

I can modify the extent to which each of these handles can go, but going out of bounds can be dangerous because one could end up accidentally placing the handles out of bounds, and have no means to return but manually alter or delete the program's configuration.

**Comment by Cuperino** [comment]
I feel so embarrassed because I'm still having trouble picturing what you mean...
Could you maybe add pictures to your explanation?

**Comment by videosmith** [comment]
Let's say you drag the left margin in halfway, the right margin currently follows. What you end up with is a narrow column of scrollable text in the center of the screen.
Now select a future button to position that narrow column on the left or right side of the screen.

**Comment by Cuperino** [comment]
But you can use the handle on the right side to offset the resized text either left or right up to the initial edges... Adding those buttons would be redundant, albeit more evident.

**Comment by Cuperino** [comment]
Maybe the right handle should become brighter when the text has been resized, so it becomes more evident that it can be grabbed.

**Comment by videosmith** [comment]
I never knew that. Thank you!
    On Wednesday, February 1, 2023, 05:14:35 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


But you can use the handle on the right side to offset the resized text either left or right up to the initial edges... Adding those buttons would be redundant, albeit more evident.

**Comment by videosmith** [comment]
Or a cursor change to a directional arrow?Either way, precisely what I needed!
    On Wednesday, February 1, 2023, 05:16:40 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Maybe the right handle should become brighter when the text has been resized, so it becomes more evident that it can be grabbed.

**Comment by Cuperino** [comment]
That feature was thought out for use in cellphones, but I'm happy to see it also serves your purpose!

I'll add something to make to make it more noticeable.
