### ISSUE TITLE
Find/replace (current or All)

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#156]
**Is your feature request related to a problem or a limitation? Please describe...**

The current search function is excellent... particularly the search as you type and that the search window stays open when toggled.

Today I had a client that wanted 20+ instances of a business name in a script replaced with another phrase. 

Would be helpful if the operator could perform a Replace/Replace All instead of retyping each instance.

Also could the highlighted word(s) be immediately modified without re-selecting? (I assume it's a focus issue)

**Comment by Cuperino** [comment]
I don't remember why, but I actually added code to clear the selection upon closing the Find interface. That seems so wrong in retrospect. Fixing.

Regarding the Replace, yes, these must be added.

**Comment by Cuperino** [comment]
Search and Replace has been added to the v1.2 branch, along with support for search with regular expressions.

![image](https://user-images.githubusercontent.com/1840407/219973611-b5557468-3893-4057-8aa4-6ee00554967c.png)
![image](https://user-images.githubusercontent.com/1840407/219973618-a185a722-aa4b-4ad0-9843-c2b4d8ca7785.png)
