### ISSUE TITLE
Displays shouldn't be configurable with projections disabled

### ISSUE THREAD

**Issue by er3eck** [Cuperino/QPrompt#158]
**Are you ready to report?**

Before reporting a bug, use GitHub's [issues filter](https://github.com/Cuperino/QPrompt/issues) to see if the bug you've found was already reported. If it has been reported, please indicate said bug also affects you and provide details that add value to the discussion. If the bug hasn't been reported, please continue to fill out this form.

**Bug Description**
Nas últimas duas versões percebi uma mensagem quando uso a função: habilitar ou desabilitar a projeção. Se eu clico em "sim" o programa reinicia e eu tenho que reconfigurar minhas formatações, se eu clico em "Não" a mensagem se apaga e o comando não funciona. Daí eu desabilito e reabilito a segunda tela novamente.
Coloquei prints das telas e estou enviando arquivo m PDF com Print de telas pra vocês.

Me coloco a disposição para qualquer outra informação necessaria.

**Steps to Reproduce**
1.  ![image](https://user-images.githubusercontent.com/125897736/220145635-4d036417-ae78-4e0e-ba80-efc176d3b75f.png)

2.  ![image](https://user-images.githubusercontent.com/125897736/220145707-67df9556-4c78-4f4d-b742-6abecd9615e0.png)

3.

**Expected behavior**

**Detailed description of display configuration** (if applicable)
Uso um notebook Dell Inspirion 3000, 8GB de memoria, saída HDMI, Windows original, outros softwares todos originais,  com placa de vídeo Radeon 520 2gb.
Uso monitores desde 15,6, 17 e 19 polegadas, TVs de 24 até 80 polegadas e algumas vezes projetores, sempre com as resoluções sugeridas pelos fabricantes deles.

**Screenshots** (optional)
Tela 1:
![image](https://user-images.githubusercontent.com/125897736/220145081-de1539a3-216d-4233-8452-04c3507d5081.png)

Tela 2:
![image](https://user-images.githubusercontent.com/125897736/220145181-bfa2b722-f8f6-4c2a-a8f5-4ee43274b386.png)

[Mensagem de erro.pdf](https://github.com/Cuperino/QPrompt/files/10785625/Mensagem.de.erro.pdf)

**Device information**
 - QPrompt Version: 1.1.3 (v1.1/5801a58)
 - Operating System: Windows 11

**Additional context**

**Comment by Cuperino** [comment]
Atenciosamente @er3eck,

Obrigado por escrever e desculpe pelo inconveniente.

Fiz várias modificações no programa para melhorar seu desempenho e uma delas exige que o QPrompt seja reiniciado para surtir efeito. O que noto é que tive que desabilitar os botões de configurações enquanto a projeção estava desligada.

A mensagem não é um erro. É uma etapa extra que agora é necessária para oferecer um desempenho melhor do que antes.

**Comment by er3eck** [comment]
Ola....
Eu esqueci de colocar a "?" depois da palavra "mensagem de erro"... Só pra
te explicar melhor... As vezes quando estou em evento projetando o TP,
acontecem interações com outras pessoas que não são os palestrantes e os
diretores me pedem pra tirar a imagem das telas... Dai eu só desabilitava a
projeção pra pessoas não verem o texto e quando voltava a ação dos
palestrantes eu habilitava novamente.... Agora eu tenho que reiniciar o
programa....
Mas tudo bem...
Obrigado pela resposta rápida.
Depois, vou enviar algumas sugestões que  facilitariam muito meu trabalho,
claro,  se isso for possível.


https://vm.tiktok.com/ZMYByjMv7/

°°°°°°°°°°°°°°°°°°°°°°°°°°
🄴🄻🄸🄼🄰🅁 🄱🄴🄲🄺
+55 11 98895-0095

B̷͇̯̗̜̪̐̂̍̚e҈̯̘͔̬̰̋͛͆
r̶̙̝̳̖͛̒̀̽̈́e̵̥̯͍̰͎͗̀ṣ̵͇̳̀̂̉̆̅p҉̱̩͙͖̒͂̆̑̀o̶͚̙͑̓̚n̷̘͔̭̙͋̉́̈́s̶͖̗̗̗͙̏̋̂i̵͕͈̙͇͗̉̐̾b̶̝̳̜̘́͐̍̊l̴͔̳̝̯̦͛̎e̵͔̠͔̦͑̅
B̶̳͔̟̥͂̊e̶̪̙̣͗̊
s̶̤̯͓̄̒u̴͇͚̍̍̂s҉̖̖̘̩͉͂̊̚t̵͍̯͓̽͋̐ͅͅǎ̴͓̦̞́̂͌̿ͅi҉̪̘̰̱̄̾n̶̲̳͍͗̓a̸͎̰̗̘͐̐͌̃́b҈̟͇̦̋̂l̴̫̪̰̜̳̏̑̃e̷͈̬̖͕̰͂̌


Em seg., 20 de fev. de 2023 14:20, Javier O. Cordero Pérez <
***@***.***> escreveu:

**Comment by Cuperino** [comment]
> As vezes quando estou em evento projetando o TP,
acontecem interações com outras pessoas que não são os palestrantes e os
diretores me pedem pra tirar a imagem das telas... Dai eu só desabilitava a
projeção pra pessoas não verem o texto e quando voltava a ação dos
palestrantes eu habilitava novamente...

Entendo. Obrigado pela explicação. Uma possível solução seria ter um segundo botão para ocultar o texto.

> Depois, vou enviar algumas sugestões que  facilitariam muito meu trabalho

Por favor, envie tudo o que você precisa. Quanto mais feedback, melhor o software.

**Comment by Cuperino** [comment]
> Displays shouldn't be configurable with projections disabled
The quoted bug is now fixed for the 1.1.5 and 1.2.0 branches.

@er3eck, Na reinicialização, o QPrompt altera a forma como os visuais são renderizados para otimizar o desempenho. Como você só desliga as projeções e as liga novamente, e não usaria o prompter sem as projeções, não há necessidade de reiniciar toda vez que desliga ou liga as projeções.

Reprogramei o prompt de redefinição para mostrar apenas uma vez se as projeções estavam inicialmente ativadas e estão sendo desativadas. Isso significa que você só precisa dizer não na primeira vez e depois pode continuar usando o QPrompt normalmente. Este mod também estará disponível em 1.1.5.

**Comment by er3eck** [comment]
Legal ....
Obrigado

°°°°°°°°°°°°°°°°°°°°°°°°°°
🄴🄻🄸🄼🄰🅁 🄱🄴🄲🄺
+55 11 98895-0095

B̷͇̯̗̜̪̐̂̍̚e҈̯̘͔̬̰̋͛͆
r̶̙̝̳̖͛̒̀̽̈́e̵̥̯͍̰͎͗̀ṣ̵͇̳̀̂̉̆̅p҉̱̩͙͖̒͂̆̑̀o̶͚̙͑̓̚n̷̘͔̭̙͋̉́̈́s̶͖̗̗̗͙̏̋̂i̵͕͈̙͇͗̉̐̾b̶̝̳̜̘́͐̍̊l̴͔̳̝̯̦͛̎e̵͔̠͔̦͑̅
B̶̳͔̟̥͂̊e̶̪̙̣͗̊
s̶̤̯͓̄̒u̴͇͚̍̍̂s҉̖̖̘̩͉͂̊̚t̵͍̯͓̽͋̐ͅͅǎ̴͓̦̞́̂͌̿ͅi҉̪̘̰̱̄̾n̶̲̳͍͗̓a̸͎̰̗̘͐̐͌̃́b҈̟͇̦̋̂l̴̫̪̰̜̳̏̑̃e̷͈̬̖͕̰͂̌


Em seg., 20 de fev. de 2023 17:09, Javier O. Cordero Pérez <
***@***.***> escreveu:
