### ISSUE TITLE
Animation stutter

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#171]
**Bug Description**
Not certain if this is a bug or expected behavior.

In order to avoid the mouse lag/stutter on taskbar and system menus when using Wayland/KDE Plasma in 22.04, I launched QPrompt 1.2 in Ubuntu/Xorg. The lag is gone, no freezes so far and animation is acceptable with Background Tansparency disabled.

One observation, when the app is launched, and set to full screen, the first execurion into Prompt mode results in a very slight animation stutter for a few moments, which then resolves itself not appearing until app relaunch/fullscreen again.

**Steps to Reproduce**
1. Set RPi into Ubuntu 22.04/Xorg
2. Launch Qprompt 1.2
3. Enter fullscreen mode
4. Enter Prompt mode

**Expected behavior**
Should be smooth at animation start like Plasma-KED/Wayland environment

**Screenshots** (optional)

https://user-images.githubusercontent.com/88691671/229967466-041eb886-25df-44a0-93f2-42faee1f2cd6.mp4

**Device information**
 - QPrompt Version: 1.2
 - Operating System: Raspberry Pi 400, Ubuntu 22.04/Xorg, latest updates

**Comment by Cuperino** [comment]
Desktop specific performance differences are beyond my control and the scope of the project.

The best I can do is identify performance bottlenecks within QPrompt and fix them. But if a specific environment's window manager or compositor is unable to update the screen's contents fast enough, no matter how much I optimize QPrompt, it will always perform better in some environments than others.

**Comment by videosmith** [comment]
Understood and thank you.
