### ISSUE TITLE
Allow setting modifier keys to markers

### ISSUE THREAD

**Issue by 24se7en** [Cuperino/QPrompt#172]
**Is your feature request related to a problem or a limitation? Please describe...**

**Describe the solution you'd prefer**

**Describe alternatives you've considered**

**Provide use examples**

**Comment by 24se7en** [comment]
Hi,

I really like your Autocue software but there a few functions that makes it perfect for Live Events (see attachments) 
- Artist in live situation have sets of songtitles ( > 10) and the songs all use different scrolling time for operators it would be fine also to setup and save the speed of the scrolling time from start on
- Also the text options: now you can only set the layout of the complete songtext instead of selecting some text and make them smaller or bigger (like for choir) now the artist see same layout
- Setup Autocue monitors with NDI like also Winplus do
![Songtitles](https://user-images.githubusercontent.com/128812814/230856807-5c530b15-1128-4e70-a079-fe1cfdab34be.jpg)
![Text Options Like Winplus](https://user-images.githubusercontent.com/128812814/230856812-5a15c2ad-75d6-4792-9d70-ff27aa64d322.jpg)

**Comment by Cuperino** [comment]
Hi @24se7en,

Thank you for taking your time to write these suggestions. In the future, try to file each request or suggestion as a separate issue so they can be tracked individually. What I've done is re-file your suggestion into the following issues and classify this one as duplicate:

- [Save scrolling speed per document](https://github.com/Cuperino/QPrompt/issues/174)
- [Allow resizing selected text](https://github.com/Cuperino/QPrompt/issues/173)
- [Highlight the line of text where the cursor is currently located](https://github.com/Cuperino/QPrompt/issues/175)
- [NDI Support](https://github.com/Cuperino/QPrompt/issues/41) (Duplicate)

With regards to marker points, you can access QPrompt's list of markers by pressing the first button on the Editor Toolbar:

![image](https://user-images.githubusercontent.com/1840407/230910089-1770024e-b946-4b1c-aeac-59ebe28c3638.png)
