### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by Ciao121** [Cuperino/QPrompt#194]
I think it's a feature request because I didn't find this feature already exists. If it exists... sorry about that.
I would like the ability to have Qpropmt stay "Always on top". I'm on a single screen notebook and I would like to run a Powerpoint presentation (full screen). This window is shared on a meeting so I can have anything above that windows (like qprompt) and it will not be shared. But, if I click on the Powerpoint presentation (i.e. to click to go to the next slide), this windows comes up hiding Qprompt (do not know why Qprompt also disappears from app lists and I cannot call it back with ALT+TAB. Anyway. if it would be possible to have the "Always on top" feature Qprompt will not be hidden so I could click on Pwoerpoint to change slide without loosing it.

**Comment by Cuperino** [comment]
> I think it's a feature request because I didn't find this feature already exists.

This an excellent idea. Thanks for the suggestion.

In case this helps, on Linux systems that use the KDE Plasma desktop environment, you can press `Alt-F3` to load window options, go to `More Actions` and then `Keep Above Others`, to keep the window on top. If you go to `Configure Special Window Settings`, you can also make Plasma's window manager always set this window on top. 

> disappears from app lists and I cannot call it back with ALT+TAB

I didn't know about this. It might be a bug in either QPrompt or the Qt framework with which it's built.

What version of Windows are you running?

**Comment by Cuperino** [comment]
This features isn't really related to Multi Screen Support, but code-wise it may relate, so I'm placing it under that category for now.

**Comment by Cuperino** [comment]
Hi @Ciao121, In order to test the bug you've reported, what version of Windows are you running?

**Comment by Cuperino** [comment]
Feature implemented for v1.2.
As for the bug you may have found, please provide more detail in a dedicated bug report to discuss it.
