### ISSUE TITLE
insert symbol missing

### ISSUE THREAD

**Issue by HansVanNeck** [Cuperino/QPrompt#20]
**Bug Description**

...
You cannot insert non English characters.  And our languages (Dutch, French, German) have a lot of them.

We need an insert symbol dialogue. 

**Steps to Reproduce**

1. ...
2. ...

**Expected behaviour**

Ideally would the behaviour like in Word, with if you type 'e  you get the right character.

**Detailed description of display configuration** (if applicable)

...

**Screenshots** (if applicable)
We want this (made with Imaginary);

.
![image](https://user-images.githubusercontent.com/95466879/144739993-e41a4fe7-508c-4b74-91c5-53ad0436270f.png)

**Device information**
 - Operating System: Windows 10 

**Additional context**

...

**Comment by Cuperino** [comment]
This may an issue with the specific input method / keyboard configuration in use.

QPrompt supports inputs in 182 languages, including Roman, Cyrillic, Chinese, Japanese, Korean, Thai, Arabic, Devangari, and Bengali writing systems, and is actively tested with a wide roman character set that includes the following keys: áéíóúÁÉÍÓÚàèìòùÀÈÌÙÒäëïöüÄËÏÖÜâêîôûÂÊÎÔÛñÑçÇ.

What keyboard layouts is Windows set to use?

What key combinations do you press to enter one of these keys? ( Are you making use of "dead keys" <Alt>+<e>, <'>+<e>, or "Alt codes" <Alt>+<Numpad sequence: 130> ?)

What language is the Windows system set to?

**Comment by Cuperino** [comment]
Hello @HansVanNeck,

I wasn't able to replicate this particular bug. I'm using a "French / English (US) International Keyboard layout with dead keys", more commonly known on Windows as "English (United States Intl.)"

Please answer the following questions:

- What keyboard layouts is your Windows set to use?
- What key combinations do you press to enter one of the keys you require to input?
- What language is your Windows system set to?
