### ISSUE TITLE
Auto font resizing

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#208]
It would be nice to have an optional preference whereby the text automatically switches to the 'small font' mode in Edit and 'normal font' in Prompting

**Comment by Cuperino** [comment]
I don't think this should need to be toggled when exiting edit mode and entering the other modes...

What if the small font toggle only showed small fonts while in edit mode? Would that work for you?

**Comment by videosmith** [comment]
That would be helpful when clients want to edit and need to see more script for context.
