### ISSUE TITLE
Font action from right click context menu isn't working

### ISSUE THREAD

**Issue by Cuperino** [Cuperino/QPrompt#210]
### Discussed in https://github.com/Cuperino/QPrompt/discussions/209#discussioncomment-6788111

<div type='discussions-op-text'>

<sup>Originally posted by **24se7en** August 22, 2023</sup>
i click with my right mouse button and select Font but nothing happened</div>

**Comment by 24se7en** [comment]
Sorry... i really like Qprompt one of the best autocue software for my job
I am working on PC Windows 10 and 11, I use your version : 1.2.0 (v1.2/bc58e78) can you give me a link where i can download the right version please
