### ISSUE TITLE
Slight video tearing in full screen on RPi 400

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#211]
**Bug Description**
When QPrompt is in full screen mode only, slight video tearing at the very top while scrolling. 

Compositor is disabled.
Transparency disabled.
Projections disabled.

**Expected behavior**
Should animate same as in Windowed mode.

**Device information**
 - QPrompt Version: 1.2 r6
 - Operating System: Raspbian Bullseye, latest updates
![20230901_180603](https://github.com/Cuperino/QPrompt/assets/88691671/90d1402f-44ea-4f2a-9826-f020d5ceb01e)

**Comment by Cuperino** [comment]
This is an OS/desktop environment/window manager issue, where the OS, desktop environment, or window manager changes how it paints windows when a window is in full screen.
