### ISSUE TITLE
Download says it is "damaged"

### ISSUE THREAD

**Issue by hmeeker** [Cuperino/QPrompt#220]
I downloaded this for my Mac Studio (2x) and it says it is damaged.

Does this software not work on Apple Silicon by any chance?

<img width="255" alt="Screen Shot 2023-09-28 at 3 12 19 PM" src="https://github.com/Cuperino/QPrompt/assets/81192739/2c389e18-ecab-40a3-9118-4b9533d2559e">

**Comment by Cuperino** [comment]
Hello,

I’m familiarized with the issue and in the process of fixing it. It’s a
problem with the installer, but the app works fine with a simple tweak.

Please refer to this thread for a workaround to get the current installer
working on your machine:

https://github.com/Cuperino/QPrompt/issues/150

Thank you for reporting the issue, and sorry for the inconvenience.

Cheers,
Javier

**Comment by Cuperino** [comment]
closing as duplicate
