### ISSUE TITLE
Secondary monitor mirroring

### ISSUE THREAD

**Issue by Vlitx** [Cuperino/QPrompt#221]
A feature to mirror only the secondary monitor , that way the producers can see what the conductor is reading in real time, flip Q has this feature and its what makes it a standard in television

**Comment by Cuperino** [comment]
QPrompt has this feature. To use it, go to Screens > Enable Projections,
and restart the app when prompted, you will only need to do this once
unless you disable the feature later.

Then go to Screens, and click on the display you wish to project to to
enable it. Clicking on it multiple times will change its flip
configuration. You can also flip from the duplicate instance.

Hope this helps, and please let me know how you find the feature’s
performance. I need to re-program it for software maintenance reasons, and
it would be nice to see how it stands up compared to other software.

Thank you for requesting features and for using QPrompt!

Best regards,
Javier

**Comment by Cuperino** [comment]
Closing as already implemented for this is already in the program. I may re-open it or start a new issue based on feedback provided.
