### ISSUE TITLE
Hide contextual menu while prompting option

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#230]
Is it possible to suppress this contextual menu while in prompt mode?
I accidentally right-clicked while scrolling and could not quickly get did of it.

**Provide use examples**

![20231103_143248](https://github.com/Cuperino/QPrompt/assets/88691671/02965e7c-ca07-4f55-955a-924b093376c9)

**Comment by Cuperino** [comment]
Done. Fixed in https://github.com/Cuperino/QPrompt/commit/c227bcb3c8a5e3f3ac8a0bbe24d929403a840661
