### ISSUE TITLE
Font formatting window only affects font selection; all other values are lost

### ISSUE THREAD

**Issue by HansVanNeck** [Cuperino/QPrompt#25]
**Bug Description**
Font formatting window only affects font selection; all other values are lost

**Steps to Reproduce**
1 Open the file in the attachment
2. St the Font size to 100% in the Font size adjustor  (I know, too small, but 100% is of course our standard).
3. See below

![image](https://user-images.githubusercontent.com/95466879/145373491-f6ea5e27-0568-4898-bdf6-a84113107337.png)
5. Try to change the red lines to the default font, and make it italic

![image](https://user-images.githubusercontent.com/95466879/145374084-53eb1f16-6b93-46f9-8b10-e6996ff9c3b8.png)

5.  No effect. 

**Expected behavior**

Formatting works

**Detailed description of display configuration** (if applicable)
Windows 10, 4k Screen.

**Screenshots** (if applicable)
See above

**Device information**
 - Operating System: Windows 10
 - QPrompt Version: 1.0.0 beta-005

**Additional context**
The file was original created in Imaginary teleprompter

[G0240NL_VeldK.zip](https://github.com/Cuperino/QPrompt/files/7684022/G0240NL_VeldK.zip)

**Comment by Cuperino** [comment]
I've replaced the previous Font Settings dialog, which was provided by the Qt framework, with a custom made one that is much simpler. The ability to choose system fonts was the reason a font dialog was added in the first place. The new dialog does only that: provide font selection.

**Comment by Cuperino** [comment]
I forgot to mention, this fix will be out in the next release, which should come out soon.
Sorry this took so long to fix. I didn't have the skills to fix this at the time, and this was a low priority issue.
