### ISSUE TITLE
Timer underestimate real processed time

### ISSUE THREAD

**Issue by HansVanNeck** [Cuperino/QPrompt#26]
**Bug Description**

The timer underestimates the real time with 10%. .

**Steps to Reproduce**

1.  See attachment. The time i 00:06:04. 
2. If you yse it in teleprompter mode it taks 00:06:41

**Expected behaviour**

The timer must be exact on the second. 

**Detailed description of display configuration** (if applicable)
![image](https://user-images.githubusercontent.com/95466879/145716396-e0e2e11d-64a6-4f37-96ac-77e281047892.png)

Velocity 6.  

**Screenshots** (if applicable)

...

**Device information**
 - Operating System: [e.g. Linux, Windows, macOS, iOS, or Android]
 - QPrompt Version: [e.g. 1.0.0-beta-003]

**Additional context**
This is  a showstopper for us. Without reliable  timing, we cannot use the application.
.
[G0210NL_Ewb.zip](https://github.com/Cuperino/QPrompt/files/7698910/G0210NL_Ewb.zip)

**Comment by Cuperino** [comment]
I'm sorry this makes the app unsuitable for your workflow.

I already knew the timer's implementation was inaccurate for scripts of long duration; but this shows it is actually worse than what I was previously able to measure, affecting scripts of short duration as well. I already have a solution planned, but it requires refactoring code. I'm afraid that I won't be able to make these changes before January.

My apologies. I will keep you posted if anything changes.

**Comment by HansVanNeck** [comment]
It is always good to refactor code.
In the mean time we will use our current application teleprompter Pro.
However that application has an accurate time, but has extremely weak file management.
If you have a new version I will be glad to test it again.

**Comment by Cuperino** [comment]
Thought of a simpler implementation that's not as performant as the one I was planning on using, but was faster to code and is precise to the second. The changes to the code already up. I'll make new binaries for all platforms and upload them as beta-006 in the upcoming days.

I'll share the link with you here as soon a they're up.

**Comment by Cuperino** [comment]
Fix ready for download at:
[![Download QPrompt](https://a.fsdn.com/con/app/sf-download-button)](https://sourceforge.net/projects/qprompt/files/latest/download)
