### ISSUE TITLE
Ubuntu install question

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#33]
Somewhat off topic for your app...
I downloaded the pertinent ubuntu desktop 21.10 os for my Raspberry pi 4b as directed.
However it hangs on launching... is it possible my Pis are 32 bit- and if so, will your app work in that os?

![20220110_194300](https://user-images.githubusercontent.com/88691671/148862087-532f7732-fda9-4f79-aca1-da5359b240ba.jpg)
![20220110_194303](https://user-images.githubusercontent.com/88691671/148862134-35c1101a-38de-4269-a635-15d5601b911f.jpg)
![20220110_194324](https://user-images.githubusercontent.com/88691671/148862173-31212b22-a059-4863-8430-7f7d45486611.jpg)
![20220110_194353](https://user-images.githubusercontent.com/88691671/148862235-7c5e1b9d-33b7-486d-831d-b00354bc64eb.jpg)

**Comment by Cuperino** [comment]
This is probably a problem with Gnome or Ubuntu itself. I had a similar issue with Fedora on a Raspberry Pi 3b+. It failed to boot because it needed 4 GB or more of RAM an older RPi models bring only 1 GB.

**Comment by Cuperino** [comment]
Raspberry Pi model 4 comes with an arm64 CPU, therefore it can boot both 32 and 64 bit arm OSs.

**Comment by Cuperino** [comment]
Try using the deb package for QPrompt 1.0.0 once again on Raspberry Pi OS 64 bit. I just fixed issue #28 by building QPrompt on Debian 11 arm64. It should work on Raspberry Pi OS.

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/

**Comment by videosmith** [comment]
Wiil do, thank you.
I thought there were performance issues with your apps using raspian 64?
    On Monday, January 10, 2022, 11:03:44 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Try using the deb package for QPrompt 1.0.0 once again on Raspberry Pi OS 64 bit. I just fixed issue #28 by building QPrompt on Debian 11 arm64. It should work on Raspberry Pi OS.

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cuperino** [comment]
No, the issue was particularly with Flatpak on the Raspberry Pi. Deb installations perform faster because there's no container abstraction between the app and the OS.

**Comment by videosmith** [comment]
Installed and working! Thank you!
