### ISSUE TITLE
Background color not saving

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#45]
**Bug Description**

When selecting a background color, works as expected, however when either saving a file or closing the program, the selection is discarded.

**Expected behavior**

Background color would be retained as app defaults upon closing.

**Detailed description of display configuration** (if applicable)

**Device information**
 - Operating System: [Debian Bullseye 64, latest updates]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
This is a bug.

**Comment by Cuperino** [comment]
Issue fixed for the next release.
