### ISSUE TITLE
Text/highlight color issue

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#50]
Cannot apply color attributes to selected text using the same color twice.

**Steps to Reproduce**

1. Select a word from your sample text.
2. Select an alternate color for text and/or highlight.
3. Select another word, attempt using the same color(s), no change.
4. Select different color, works as expected.

**Expected behavior**

Text should change to selected color(s)

**Detailed description of display configuration** (if applicable)

RPI 4 Bullseye 64 latest updates, 1280x720, single monitor.

**Device information**
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
Issue fixed for maintenance release.

**Comment by Cuperino** [comment]
WIP
