### ISSUE TITLE
Pasted text broken into paragraphs at random places

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#57]
Pasted text is broken at random places.

**Steps to Reproduce**

1. Open a simple text document in Word or LibreOffice Writer, select all text and copy
2. Paste into new document window in app, text is parsed in random places.
3. Paste into text editor, select all and paste that into a new document window in app, behaves as expected.

**Expected behavior**
Should maintain basic formatting.

**Screenshots** (if applicable)

...
![Writer](https://user-images.githubusercontent.com/88691671/152579267-8f76fac3-23ef-46b0-8af3-4e9db2ecfcbd.png)

![Paste from Word](https://user-images.githubusercontent.com/88691671/152579314-891f4365-ffe6-4528-92a6-aba77e871d9f.png)

![text](https://user-images.githubusercontent.com/88691671/152579989-4f211291-23ff-4b2b-a990-3f7c49e84dca.png)

![paste from text](https://user-images.githubusercontent.com/88691671/152580027-2092a9a2-7798-44c0-90db-dbf94a90757a.png)

**Device information**
 - Operating System: [Debian Bullseye 64 latest updates RPi 4b]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
The bug seems to be caused by the text parser used to partially clean formatting from pasted contents.

While I fix this bug, use Ctrl+Shift+V to paste text without formatting. It will preserve the line endings from the original document.

**Comment by Cuperino** [comment]
Bug fixed for next release.
