### ISSUE TITLE
Anchors lost on file save

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#58]
Anchors not saving with html file.

**Steps to Reproduce**

1. Select text in your default script, apply anchor, note that the over/underscores indicate the tag was added as does the Marker list window.
2. Save as html, clear and reload the script.  The over/underscores are still present, however the tag is missing from the Marker list window.

**Expected behavior**

Tags should save with the html file.

**Screenshots** (if applicable)

...
![initial anchor setting](https://user-images.githubusercontent.com/88691671/152581519-f6fff3be-20c6-493a-a934-fa836e50cfee.png)

![after reloading](https://user-images.githubusercontent.com/88691671/152581537-a73887c0-fc6b-43f9-88d2-03d9bb5f743d.png)

**Device information**
 - Operating System: [Debian Bullseye 64 latest updates, RPi 4b]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
Issue fixed for next release.
