### ISSUE TITLE
Scrolling to top of script exits prompt mode

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#60]
**Bug Description**
Scrolling to top of script exits prompt mode 

**Expected behavior**

Should remain in prompt mode.

**Device information**
 - Operating System: [Debian Bullseye 64, latest updates, RPi 4b]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
While trying to replicate I realized you're manually "rewinding" the prompter to the start. You can also double click on the big rectangle bellow the prompter's contents to go back to the start. If you're midway through, you can also press Page-Up to rewind faster.

This is still a bug. Thank you for reporting it!

**Comment by Cuperino** [comment]
Fixed for next release.

**Comment by Cuperino** [comment]
Re-opening due to bug in fix. At start and at end checks outputs are inconsistent.

**Comment by Cuperino** [comment]
Solved for next release.
