### ISSUE TITLE
Velocity setting does not persist on mode change

### ISSUE THREAD

**Issue by hafner** [Cuperino/QPrompt#61]
If I'm in the middle of a recording and have to switch modes to edit the script when I return, the velocity is set back to 3 not whatever I had it at. This happens for me a lot near the end of the script as the prompter changes modes at the end and then the velocity is reset, making it more difficult than it needs to be as I sadly require a lot of takes.

**Comment by Cuperino** [comment]
I hadn't thought about this. This is a very good point!

Right now the initial velocity can be set to a closer value to that which you intent to use by clicking on the stopwatch icon on the editor toolbar and setting the start velocity. I can make it so this value is automatically updated when the prompter reaches the end.

**Comment by Cuperino** [comment]
It could also be updated whenever the user switches from prompt mode to edit mode.
