### ISSUE TITLE
Left paragraph alignment lost on file save

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#62]
**Bug Description**

Text decorations not persistent between file saves.

**Steps to Reproduce**

1. Adjust text decorations to default script
2. Save file in html format
3. Restart app
4. Load html file
5. Bold and justification reset

**Expected behavior**

Decorations should save with html file.

**Detailed description of display configuration** (if applicable)

App run in HDMI 2 monitor only, screens and projections off

**Screenshots** (if applicable)
![Screenshot from 2022-02-10 13-32-46](https://user-images.githubusercontent.com/88691671/153691681-fbdd2ff4-c141-43fb-9d06-361c49cd279d.png)

![Screenshot from 2022-02-10 13-36-21](https://user-images.githubusercontent.com/88691671/153691686-933498d3-9273-48e0-8891-0c0f23212085.png)

**Device information**
 - Operating System: [Debian Bullseye 64 latest updates, RPi 4b]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
I managed to replicate the issue with the `left` text alignment. I believe the bug comes from having the default orientation set to center instead of left.

Bold worked fine in all my tests. Could you describe the steps you followed with more detail, in order to replicate the exact situation?

**Comment by videosmith** [comment]
1. Launch your app <v. 1.0.0 <main/177fa70>, (RPI 4b, Debian 64 Bullseye, latest updates).
2. Drag/select the first line of the default script below the embedded logo.
3. Select Bold attribute.
4. Save as test.html (selecting html file format in save requester).
5. Close/re-open the app.
6. Open the saved html file-bold attribute on prior selected text missing.
7. works as expected in the Windows version on my intel laptop.
    On Friday, February 11, 2022, 10:40:12 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


I managed to replicate the issue with the left text alignment. I believe the bug comes from having the default orientation set to center instead of left.

Bold worked fine in all my tests. Could you describe the steps you followed with more detail, in order to replicate the exact situation?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cuperino** [comment]
Issue fixed for next update.
