### ISSUE TITLE
Make next and previous anchor shortcut customization independent from move backwards and forwards

### ISSUE THREAD

**Issue by avlinkus** [Cuperino/QPrompt#65]
**Is your feature request related to a problem or a limitation? Please describe...**

Hi Cuperino,
First congratulations for your Qprompt project. I have tried a lot of prompter softwares and never find an all-in-one solution. Imaginary Teleprompter and Qprompt are nearly perfect. So, all my congratulations for the great job you've done.
I will be pleased to help you in anyway. Do not hesitate.

Feature request :
Other shortcuts could be very useful : like F9, Space, etc.
Especialy to access directly to the next or previous anchor... these shortcuts will be available to some device like ShuttleExpress or StreamDeck ;)

Labelling buttons could be a nice way to help users in their decisions.

**Describe the solution you'd preffer**

...

**Describe alternatives you've considered**

...

**Provide use examples**

...

**Comment by Cuperino** [comment]
First, thank you for your kind words.

QPrompt has shortcuts similar to those of Imaginary Teleprompter. What it is currently lacking is documentation letting users know about these shortcuts. If you go to `Menu > Control Settings > Keyboard Inputs`, you'll be able to see the current shortcuts and change them to your liking. You will find there's no shortcut specific to the next and previous anchors, but what's really happening is you press `Control` followed by `Page Up` and `Page Down` to  move between anchors.

Maybe I should make them separately configurable keys... That would make it easier to configure with Contour's devices.

**Comment by avlinkus** [comment]
It works perfectly! Very useful. It necessary to know.

**Comment by Cuperino** [comment]
I've just added the ability to configure go to previous and next anchor shortcuts independently of the shortcuts to move backwards and forwards. This feature will be available with the next release.
