### ISSUE TITLE
Esc key supressed

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#69]
Under certain circumstances, you cannot exit the prompt mode with the ESC key

**Steps to Reproduce**

1. Click Start Prompter
2. Click Start Prompting
3. Click Fullscreen
4. Attempt to exit prompting with the ESC key, no response, must use blue icon at screen bottom.
5. If you enter Fullscreen first, then enable Prompting, ESC works as expected.

**Detailed description of display configuration** (if applicable)
App running on HDMI 2 only

**Device information**
 - Operating System: [RPI 4b, Debian Bullseye 64, latest updates]
 - QPrompt Version: [1.0.0]

**Comment by Cuperino** [comment]
Issue fixed for next release.
