### ISSUE TITLE
Requires the button to turn the page function, so that the remote control can be used more naturally

### ISSUE THREAD

**Issue by fxbd** [Cuperino/QPrompt#71]
**Is your feature request related to a problem or a limitation? Please describe...**

...

**Describe the solution you'd preffer**

...

**Describe alternatives you've considered**

...

**Provide use examples**

...

**Comment by Cuperino** [comment]
Hello @fxbd,

Could you provide more details please? I'm not sure what you mean by turn page function, nor which button and remote control you are referring to.

**Comment by Cuperino** [comment]
I'm going to close the issue until more details are provided. Feel free to re-open, I apologize for the inconvenience.
