### ISSUE TITLE
Prompt mode unexpectedly exits

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#77]
When setting a scroll speed and selecting pause with the space bar, Prompt mode exits to edit mode.

**Steps to Reproduce**
1.  Loaded a long script (not certain if that matters, mine was 2:38:47) 
2.  Font size 89%
3.  Select Fullscreen
4.  Select Black as background color
5. Select the Down Arrow key repeatedly until a reasonable scroll speed achieved
6. Select pause with the space bar
7.  Wait approximately 10-20 minutes
8.  App exits prompt mode back to edit mode

Should stay in prompt mode

**Detailed description of display configuration** (if applicable)
Raspberry Pi 4, 4GB, HDMI single channel, 720p

**Device information**
 - QPrompt Version: 1.0.0
 - Operating System: Debian Bullseye 64, latest updates

**Comment by Cuperino** [comment]
Bug confirmed. Apparently the animation's timer continued to run in the background, triggering the animation complete event when it completed, even though the animation had already been stopped.

**Comment by Cuperino** [comment]
Bug fixed for next release.
