### ISSUE TITLE
Uninstall error message

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#80]
**Bug Description**
When attempting to uninstall Qprompt, the following message is displayed... unable to proceed, only Cancel the uninstall procedure.

**Steps to Reproduce**
1. Select either the app from the control panel Uninstall applet or run the uninstall scrip in the programs directory (also tried with Administrator priveledges)
2. Message always displayed

**Expected behavior**
Program should uninstall

**Screenshots** (optional)
https://photos.app.goo.gl/3fFnFAgpcD4iEWsg7
https://linksharing.samsungcloud.com/pbsdEnRxHAAG
**Device information**
 - QPrompt Version:
 - Operating System: win 7 sp1

**Comment by Cuperino** [comment]
That error usually appears on Windows when someone attempts to update or remove software that is currently being used. I managed to replicate the bug by opening and closing QPrompt, and then attempting to uninstall. It seems to be that even though QPrompt closes properly, Qt's D-Bus library for inter-process communication continues to run in the background, causing the prompt. Answering yes to killing said process allows the uninstaller to continue normally. My tests were done on Windows 10.

I don't think I can do anything about DBus, for QPrompt itself seems to be closing properly. Restarting Windows will also close DBus automatically, allowing QPrompt to be uninstalled without prompts.

FYI, QPrompt 1.x is supported from Windows 7 onward. When the transition to Qt 6 is complete in more or less a year from now, only Windows 10 onward will be supported.
