### ISSUE TITLE
Occasional app crash when invoking the Prompt mode

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#97]
**Bug Description**
When switching from Edit to Prompt mode, either by mouse click or hotkey, the program closes. Will provide more info, if I can reproduce the issue on demand.

**Steps to Reproduce**
1. Difficult as it only happens occasionally.
2. Clicking on the Start Prompting button or a keyboard shortcut (through a ShuttleXpress script) crashes the program.
3. Only other app open is the resident code for the ShuttleXpress driver.

**Expected behavior**
Should go into prompt mode as it usually does

**Detailed description of display configuration** (if applicable)
RPi 400, Raspberry Pi OS, latest updates, 
Same 1.0.0 release build of QPrompt as in the past.
HDMI 0 only in use

**Comment by Cuperino** [comment]
Is transparency enabled when this happens?

**Comment by videosmith** [comment]
I wonder if this is related to #115?

**Comment by Cuperino** [comment]
It could be related. The list of bookmarks gets regenerated in various specific circumstances.

**Comment by Cuperino** [comment]
It turns out this bug is unrelated to #115 because #115 wasn't caused by a dangling pointer, but by an out of bounds access attempt that is never executed while invoking prompt mode.

**Comment by Cuperino** [comment]
Let me know if this bug ever manifests itself again. I think there's a chance I might've squashed it in v1.1.1.

**Comment by videosmith** [comment]
No. Only opeeating in full screen selecting prevoius marker - even if only one marker placed
    On Wednesday, July 27, 2022, 03:17:01 PM EDT, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Is transparency enabled when this happens?

**Comment by Cuperino** [comment]
Does this crash still occur? I have reason to believe I may have fixed this issue in v1.1.1, but I have no way to be sure because I haven't been able to replicate it.

**Comment by videosmith** [comment]
So far, no. Still on 1.1.1 though due to animation issues with 1.1.2 on RPi.
    On Tuesday, October 11, 2022 at 12:27:33 PM EDT, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Does this crash still occur? I have reason to believe I may have fixed this issue in v1.1.1, but I have no way to be sure because I haven't been able to replicate it.

**Comment by Cuperino** [comment]
Alright. If the issue doesn't happen again and no one reports an issue that might be related, I may to close this issue as "potentially solved" after v1.2.1 or a later release.

**Comment by Cuperino** [comment]
This issue seems to have been successfully solved long ago, and the startup crash that that was fixed in v1.2.0-03 is not related to this. Closing as solved.
